### ISSUE TITLE
Incorrect footprint for BME680

### ISSUE THREAD

**Issue by LukaszWoj** [adafruit/Adafruit-BME680-PCB#1]
The PCB file has the incorrect footprint - the BME280 is in the place of the BME680.

This results in the pitch of the PCB pads not being 0.8mm and instead are 0.65mm and will have soldering problems.

The schematic object also causes confusion, it is marked **BMEx80** which can lead to thinking that the BME280 and BME680 are interchangeable which is not the case..

Thank you!

**Comment by caternuson** [comment]
Good catch. This repo just needs updated with latest PCB files.

**Comment by ATM-HSW** [comment]
The CAD files still contains the wrong packages - it's a BME280 not a BME680
An update would be great.

**Comment by ATM-HSW** [comment]
I think, this issue can be closed because it is solved.
