### ISSUE TITLE
Update PCB with Stemma QT version

### ISSUE THREAD

**Issue by timonvo** [adafruit/Adafruit-BME680-PCB#2]
In August 2020 the PCB was redesigned with Stemma QT support (https://www.adafruit.com/product/3660). Would it be possible to get the updated schematics uploaded to this repo?

**Comment by ATM-HSW** [comment]
Any news about uploading the Stemma QT version of the sensor board?

**Comment by kattni** [comment]
I missed this one! I'll get it uploaded by next week!

**Comment by ATM-HSW** [comment]
I think, this issue can be closed because it is solved.
